services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: happielearning/mongo:1.0.0
    container_name: mongo
    volumes:
      - mongodb:/data/db
  
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis:/data

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: happielearning/mysql:1.0.0
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: "roboshop"
      RABBITMQ_DEFAULT_PASS: "roboshop123"
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: happielearning/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: happielearning/user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb
  
  cart:
    build:
      context: ./cart
      dockerfile: ./Dockerfile
    image: happielearning/cart:1.0.0
    container_name: cart
    depends_on:
      - mongodb
      - redis

  shipping:
    build: 
      context: ./shipping
      dockerfile: Dockerfile
    image: happielearning/shipping:1.0.0 
    container_name: shipping
    depends_on:
      - mysql
      - cart

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: happielearning/payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
      - rabbitmq
      - cart
      - user
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: happielearning/frontend:1.0.0
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - catalogue
      - user
      - cart
      - payment
      - shipping

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if set to true, we have to create manually using `docker network create roboshop` before running the compose file

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq: